export const GATEWAY_PROVIDERS = {
  STRIPE: 'STRIPE',
  AUTHORIZE_NET: 'AUTHORIZE_NET',
  NMI: 'NMI',
  CARDPOINTE: 'CARDPOINTE',
  CUSTOM: 'CUSTOM'
} as const;

export const ENVIRONMENTS = {
  SANDBOX: 'SANDBOX',
  PRODUCTION: 'PRODUCTION'
} as const;

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  VOIDED: 'VOIDED'
} as const;
